<?php

require getcwd() . "/../vendor/autoload.php";

use horstoeko\ubl\UblDocumentBuilderXRechnung;

$builder = (new UblDocumentBuilderXRechnung)
    ->setDocumentNumber("0000123456")
    ->setDocumentDate(DateTime::createFromFormat("Y-m-d", "2017-12-11"))
    ->setDocumentDueDate(DateTime::createFromFormat("Y-m-d", "2018-01-10"))
    ->setDocumentType("380")
    ->setDocumentNote("[Invoice note]")
    ->setDocumentCurrencies("EUR")
    ->setDocumentBuyerReference("11002002-98765-43")
    ->setDocumentBuyerOrderNo("10520")
    ->setDocumentContractReference("0000000752")
    ->addDocumentAdditionalReference("01_15_Anhang_01.pdf", "", "", "Aufschlüsselung der einzelnen Leistungspositionen")
    ->setFileAttachmentToAdditionalReference(dirname(__FILE__) . "/attachment.pdf")
    ->setDocumentProjectReference("Entwicklung System")
    ->initDocumentSeller()
    ->setDocumentSellerName("[Seller name]")
    ->setDocumentSellerPostalAddress("[Seller street]", "", "", "[Seller city]", "10623", "", "DE")
    ->setDocumentSellerVATIdentifier("DE123456789")
    ->setDocumentSellerLegalEntity("[Seller name]")
    ->setDocumentSellerContact("[Seller contact person]", "[Seller contact telephone number]", "contact@seller.de")
    ->initDocumentBuyer()
    ->setDocumentBuyerName("[Buyer name]")
    ->setDocumentBuyerPostalAddress("[Buyer street]", "", "", "[Buyer city]", "12345", "", "DE")
    ->setDocumentBuyerLegalEntity("[Buyer name]")
    ->setDocumentBuyerContact("[Buyer contact person]", "", "buyer@contact.com")
    ->setDocumentPaymentMeansToPaymentCard("41234", "mapped-from-cii", "[Payment card holder name]")
    ->setDocumentPaymentTerms("Bei Zahlungen binnen 14 Tagen, 2% Skonto")
    ->initDocumentTaxTotal()
    ->initDocumentTaxSubTotal()
    ->setDocumentTaxAmounts(8980, 1706.2)
    ->setDocumentTaxScheme("S", "VAT", 19.0)
    ->setDocumentSummation(8980, 8980, 10686.2, 10686.2)
    ->addNewDocumentPosition("0")
    ->setDocumentPositionQuantity(1, "XPP")
    ->setDocumentPositionItem("Anforderungsaufnahme", "Anforderungmanagament", "", "1034")
    ->setDocumentPositionTaxScheme("S", "VAT", 19.0)
    ->setDocumentPositionPrice(850)
    ->setDocumentPositionTotalAmount(850)
    ->addNewDocumentPosition("1")
    ->setDocumentPositionQuantity(1, "XPP")
    ->setDocumentPositionItem("Lastenheft", "Erstellung Lastenheft bis Abnahme", "", "1035")
    ->setDocumentPositionTaxScheme("S", "VAT", 19.0)
    ->setDocumentPositionPrice(2986)
    ->setDocumentPositionTotalAmount(2986)
    ->addNewDocumentPosition("2")
    ->setDocumentPositionQuantity(1, "XPP")
    ->setDocumentPositionItem("Pflichtenheft", "Erstellung Pflichtenheft bis Abnahme", "", "1036")
    ->setDocumentPositionTaxScheme("S", "VAT", 19.0)
    ->setDocumentPositionPrice(2344)
    ->setDocumentPositionTotalAmount(2344)
    ->addNewDocumentPosition("3")
    ->setDocumentPositionQuantity(1, "XPP")
    ->setDocumentPositionItem("Entwicklung", "Entwicklung System bis Implementierung", "", "1037")
    ->setDocumentPositionTaxScheme("S", "VAT", 19.0)
    ->setDocumentPositionPrice(2800)
    ->setDocumentPositionTotalAmount(2800)
    ->writeFile(dirname(__FILE__) . "/Example_03.02a-INVOICE_ubl_XRechnungBuilder.xml");
